### ISSUE TITLE
Update license terms

### ISSUE THREAD

**Issue by maulik-modi** [sfmskywalker/Elsa#31]
That's a good start. Kindly add license terms.

There are lot of open source workflow engines in Java but only handful in .NET that is open source on .NET Core. [Slickflow](https://github.com/besley/Slickflow) is there but do not see active movement.

**Comment by sfmskywalker** [comment]
Thanks for the encouragement! I just added the [license file](https://github.com/sfmskywalker/Elsa/blob/develop/LICENSE).
